```{r predtreatdisc, cache=cacheon}

funcpred <- function(efcat, medpre, medpost, valmedpre = "Yes", valmedpost = "No", name = efcat) {
  amod <- hf_glm_mids(formula(paste0(
    medpost, "=='", valmedpost, "' ~ ", paste(modvars, collapse = " + ")
  )),
  data = imp,
  subset = expr(sos_location == "HF in-patient" & shf_ef_cat %in% efcat & !!sym(medpre) == valmedpre)
  )
  asmod <- summary(pool(amod))

  nval <- length(asmod$term)
  terms <- as.character(asmod$term[2:nval])
  units <- rep(1, nval - 1)
  units[terms %in% c("shf_age", "shf_map", "shf_heartrate")] <- 10
  terms[terms %in% c("shf_age", "shf_map", "shf_heartrate")] <- paste0(terms[terms %in% c("shf_age", "shf_map", "shf_heartrate")], "*")
  out <- tibble(
    Variable = terms,
    !!sym(name) := paste0(
      fn(exp(asmod$estimate[2:nval])^units, dig = 1),
      " (", fn(exp(asmod$estimate[2:nval] - global_z05 * asmod$std.error[2:nval])^units, dig = 1),
      "-", fn(exp(asmod$estimate[2:nval] + global_z05 * asmod$std.error[2:nval])^units, dig = 1), "), ",
      fn(asmod$p.value[2:nval], dig = 3, p = TRUE)
    )
  )

  checkinf <- any(str_detect(out %>% pull(!!sym(name)), "Inf"))
  
  if (checkinf) {
    out[, 2] <- "-"
  }
    
  return(out)
}
```

```{r predtreatdiscmra, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(efcat = "HFrEF", medpre = "ddr_mra_prior", medpost = "ddr_mra_post")
ref8m <- funcpred(efcat = "HFrEF", medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", name = "HFrEF (2 dd/8mo)")

mref <- funcpred(efcat = "HFmrEF", medpre = "ddr_mra_prior", medpost = "ddr_mra_post")
mref8m <- funcpred(efcat = "HFmrEF", medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", name = "HFmrEF (2 dd/8mo)")

ef <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_mra_prior", medpost = "ddr_mra_post", name = "EF combined")
ef8m <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", name = "EF combined (2 dd/8mo)")

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_mra_disc_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment discontinuation MRA",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```


```{r predtreatdiscrasi, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(efcat = "HFrEF", medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post")
ref8m <- funcpred(efcat = "HFrEF", medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post", name = "HFrEF (2 dd/8mo)")

mref <- funcpred(efcat = "HFmrEF", medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post")
mref8m <- funcpred(efcat = "HFmrEF", medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post", name = "HFmrEF (2 dd/8mo)")

ef <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", name = "EF combined")
ef8m <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post", name = "EF combined (2 dd/8mo)")

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_rasi_disc_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment discontinuation RASi/ARNi",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```

```{r predtreatdiscbbl, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(efcat = "HFrEF", medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post")
ref8m <- funcpred(efcat = "HFrEF", medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post", name = "HFrEF (2 dd/8mo)")

mref <- funcpred(efcat = "HFmrEF", medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post")
mref8m <- funcpred(efcat = "HFmrEF", medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post", name = "HFmrEF (2 dd/8mo)")

ef <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", name = "EF combined")
ef8m <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post", name = "EF combined (2 dd/8mo)")

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_bbl_disc_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment discontinuation Bbl",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```

```{r predtreatdiscloopd, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(
  efcat = "HFrEF", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post"
)
ref8m <- funcpred(
  efcat = "HFrEF", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
  name = "HFrEF (2 dd/8mo)"
)

mref <- funcpred(
  efcat = "HFmrEF", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post"
)

mref8m <- funcpred(
  efcat = "HFmrEF", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
  name = "HFmrEF (2 dd/8mo)"
)

ef <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post", name = "EF combined")
ef8m <- funcpred(
  efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_loopdiuretic_prior8m",
  medpost = "ddr_loopdiuretic_post", name = "EF combined (2 dd/8mo)"
)

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_loopd_disc_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment discontinuation Loop diuretics",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```

```{r predtreatinimra, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(efcat = "HFrEF", medpre = "ddr_mra_prior", medpost = "ddr_mra_post", valmedpre = "No", valmedpost = "Yes")
ref8m <- funcpred(efcat = "HFrEF", medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", name = "HFrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes")

mref <- funcpred(efcat = "HFmrEF", medpre = "ddr_mra_prior", medpost = "ddr_mra_post", valmedpre = "No", valmedpost = "Yes")
mref8m <- funcpred(efcat = "HFmrEF", medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", name = "HFmrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes")

ef <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_mra_prior", medpost = "ddr_mra_post", name = "EF combined", valmedpre = "No", valmedpost = "Yes")
ef8m <- funcpred(
  efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", name = "EF combined (2 dd/8mo)",
  valmedpre = "No", valmedpost = "Yes"
)

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_mra_ini_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment initiation MRA",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```

```{r predtreatinirasi, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(efcat = "HFrEF", medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", valmedpre = "No", valmedpost = "Yes")
ref8m <- funcpred(efcat = "HFrEF", medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post", name = "HFrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes")

mref <- funcpred(efcat = "HFmrEF", medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", valmedpre = "No", valmedpost = "Yes")
mref8m <- funcpred(efcat = "HFmrEF", medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post", name = "HFmrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes")

ef <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", name = "EF combined", valmedpre = "No", valmedpost = "Yes")
ef8m <- funcpred(
  efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post", name = "EF combined (2 dd/8mo)",
  valmedpre = "No", valmedpost = "Yes"
)

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_rasi_ini_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment initiation RASi/ARNi",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```

```{r predtreatinicbbl, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(efcat = "HFrEF", medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", valmedpre = "No", valmedpost = "Yes")
ref8m <- funcpred(efcat = "HFrEF", medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post", name = "HFrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes")

mref <- funcpred(efcat = "HFmrEF", medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", valmedpre = "No", valmedpost = "Yes")
mref8m <- funcpred(efcat = "HFmrEF", medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post", name = "HFmrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes")

ef <- funcpred(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", name = "EF combined", valmedpre = "No", valmedpost = "Yes")
ef8m <- funcpred(
  efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post", name = "EF combined (2 dd/8mo)",
  valmedpre = "No", valmedpost = "Yes"
)

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_bbl_ini_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment initiation Bbl",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```

```{r predtreatiniloopd, cache=cacheon, dependson="predtreatdisc"}

ref <- funcpred(
  efcat = "HFrEF", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post", valmedpre = "No", valmedpost = "Yes"
)
ref8m <- funcpred(
  efcat = "HFrEF", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
  name = "HFrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes"
)

mref <- funcpred(
  efcat = "HFmrEF", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post", valmedpre = "No", valmedpost = "Yes"
)

mref8m <- funcpred(
  efcat = "HFmrEF", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
  name = "HFmrEF (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes"
)

ef <- funcpred(
  efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post", name = "EF combined",
  valmedpre = "No", valmedpost = "Yes"
)
ef8m <- funcpred(
  efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_loopdiuretic_prior8m",
  medpost = "ddr_loopdiuretic_post", name = "EF combined (2 dd/8mo)", valmedpre = "No", valmedpost = "Yes"
)

all <- Reduce(
  function(...) {
    full_join(...,
      by = "Variable"
    )
  },
  list(ref, ref8m, mref, mref8m, ef, ef8m)
)

write.xlsx(all, paste0("./output/tabs/pred_loopd_ini_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all,
  caption = "Predictors of treatment initiation Loop diuretics",
  escape = TRUE,
  scale_down = T
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, "Adjusted OR (95% CI), p-value" = 6))
```
