```{r rephosp, cache=cacheon}

# add 1 to all hosp in order to account to initial hospitalization
rsdata <- rsdata %>%
  mutate(
    sos_out_nohosphf6m_cat = factor(case_when(
      sos_out_nohosphf6m == 0 ~ 1,
      sos_out_nohosphf6m <= 2 ~ 2,
      sos_out_nohosphf6m <= 5 ~ 3,
      sos_out_nohosphf6m >= 6 ~ 4
    ),
    levels = 1:4,
    labels = c("1", "2-3", "4-6", ">=7")
    ),
    sos_out_nohosphf1y_cat = factor(case_when(
      sos_out_nohosphf1y == 0 ~ 1,
      sos_out_nohosphf1y <= 2 ~ 2,
      sos_out_nohosphf1y <= 5 ~ 3,
      sos_out_nohosphf1y >= 6 ~ 4
    ),
    levels = 1:4,
    labels = c("1", "2-3", "4-6", ">=7")
    ),
    sos_out_nohosphf2y_cat = factor(case_when(
      sos_out_nohosphf2y == 0 ~ 1,
      sos_out_nohosphf2y <= 2 ~ 2,
      sos_out_nohosphf2y <= 5 ~ 3,
      sos_out_nohosphf2y >= 6 ~ 4
    ),
    levels = 1:4,
    labels = c("1", "2-3", "4-6", ">=7")
    ),
    sos_out_nohosphf3y_cat = factor(case_when(
      sos_out_nohosphf3y == 0 ~ 1,
      sos_out_nohosphf3y <= 2 ~ 2,
      sos_out_nohosphf3y <= 5 ~ 3,
      sos_out_nohosphf3y >= 6 ~ 4
    ),
    levels = 1:4,
    labels = c("1", "2-3", "4-6", ">=7")
    )
  )

bardatafunc <- function(data2, treat2, time, minfollowup, timevalue, postvalue2) {
  treatvar <- paste0("ddr_", treat2, "_post", time)
  hfhospvar <- paste0("sos_out_nohosphf", time, "_cat")

  bardata <- data2 %>%
    filter(
      sos_outtime_death >= minfollowup
    ) %>%
    group_by(!!sym(hfhospvar)) %>%
    count(!!sym(treatvar)) %>%
    mutate(
      freq = (n / sum(n)) * 100,
      ntot = sum(n)
    ) %>%
    ungroup() %>%
    filter(!!sym(treatvar) == postvalue2) %>%
    mutate(time = timevalue) %>%
    rename(sos_out_nohosphfall = !!sym(hfhospvar)) %>%
    select(sos_out_nohosphfall, time, ntot, n, freq)
}

reptreatbar <- function(data, treat, ymax = 100, postvalue) {
  bardata6m <- bardatafunc(
    data2 = data,
    treat2 = treat,
    time = "6m",
    minfollowup = 365,
    timevalue = 0,
    postvalue2 = postvalue
  )

  bardata1y <- bardatafunc(
    data2 = data,
    treat2 = treat,
    time = "1y",
    minfollowup = 365 * 1.5,
    timevalue = 1,
    postvalue2 = postvalue
  )

  bardata2y <- bardatafunc(
    data2 = data,
    treat2 = treat,
    time = "2y",
    minfollowup = 365 * 2.5,
    timevalue = 2,
    postvalue2 = postvalue
  )

  bardata3y <- bardatafunc(
    data2 = data,
    treat2 = treat,
    time = "3y",
    minfollowup = 365 * 3.5,
    timevalue = 3,
    postvalue2 = postvalue
  )

  bardataall <- bind_rows(bardata6m, bardata1y, bardata2y, bardata3y) %>%
    mutate(time = factor(time, levels = c(0:3), labels = c("6 months", "1 year", "2 years", "3 years")))

  cexmy <- 1.2

  # c(bottom, left, top, right)
  par(mar = c(4, 8, 2, 0) + 0.1)

  b <- barplot(freq ~ sos_out_nohosphfall + time,
    data = bardataall, beside = T, axes = F,
    ylab = "Percent discontinued",
    xlab = NA,
    ylim = c(0, ymax),
    col = global_cols[c(2, 4, 6, 8)],
    border = "white",
    cex.lab = cexmy,
    names.arg = rep(NA, 4)
  )

  text(
    x = b, y = bardataall$freq + ymax / 40, label = paste0(bardataall$n, "/", bardataall$ntot),
    cex = cexmy, col = "black", xpd = TRUE, srt = 90, adj = 0
  )

  axis(2, las = 2, cex.axis = cexmy)

  mtext("No. HFH", side = 1, line = 1, at = -5.5, adj = 0, cex = cexmy)
  mtext("Time after 1st HFH", side = 1, line = 3, at = -5.5, adj = 0, cex = cexmy)

  axis(1, at = b, rep(c("1", "2-3", "4-6", "7+"), 4), cex.axis = cexmy, line = 0, tick = FALSE, gap.axis = -10000000, las = 2)
  axis(1, at = (b[2, ] + b[3, ]) / 2, c("6 months", "1 year", "2 years", "3 years"), cex.axis = cexmy, line = 2, tick = FALSE, gap.axis = -10000000)
}
```


```{r rephospmra, fig.cap = "Repeated HF hospitalizations vs discontinuation of MRA (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data = rsdata %>% filter(
    ddr_mra_prior == "Yes",
    sos_location == "HF in-patient"
  ),
  treat = "mra", ymax = 100,
  postvalue = "No"
)
```

```{r rephospras, fig.cap = "Repeated HF hospitalizations vs discontinuation of RASi/ARNi (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data =
    rsdata %>% filter(
      ddr_rasi_prior == "Yes",
      sos_location == "HF in-patient"
    ),
  treat = "rasi", ymax = 100,
  postvalue = "No"
)
```

```{r rephospbbl, fig.cap = "Repeated HF hospitalizations vs discontinuation of Bbl (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data = rsdata %>% filter(
    ddr_bbl_prior == "Yes",
    sos_location == "HF in-patient"
  ),
  "bbl", ymax = 100,
  postvalue = "No"
)
```

```{r rephosploop, fig.cap = "Repeated HF hospitalizations vs discontinuation of Loop diuretic (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data = rsdata %>% filter(
    ddr_loopdiuretic_prior == "Yes",
    sos_location == "HF in-patient"
  ),
  "loopdiuretic", ymax = 100,
  postvalue = "No"
)
```

```{r rephospmraini, fig.cap = "Repeated HF hospitalizations vs initiation of MRA (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data = rsdata %>% filter(
    ddr_mra_prior == "No",
    sos_location == "HF in-patient"
  ),
  treat = "mra", ymax = 100,
  postvalue = "Yes"
)
```

```{r rephosprasini, fig.cap = "Repeated HF hospitalizations vs initiation of RASi/ARNi (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data =
    rsdata %>% filter(
      ddr_rasi_prior == "No",
      sos_location == "HF in-patient"
    ),
  treat = "rasi", ymax = 100,
  postvalue = "Yes"
)
```

```{r rephospbblini, fig.cap = "Repeated HF hospitalizations vs initiation of Bbl (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data = rsdata %>% filter(
    ddr_bbl_prior == "No",
    sos_location == "HF in-patient"
  ),
  "bbl", ymax = 100,
  postvalue = "Yes"
)
```

```{r rephosploopini, fig.cap = "Repeated HF hospitalizations vs initiation of Loop diuretic (HFrEF + HFmrEF), n in each group over bars", cache=cacheon, dependson="rephosp"}
reptreatbar(
  data = rsdata %>% filter(
    ddr_loopdiuretic_prior == "No",
    sos_location == "HF in-patient"
  ),
  "loopdiuretic", ymax = 100,
  postvalue = "Yes"
)
```
