```{r tabontreatallfunc, cache=cacheon}

funcdesk <- function(medpre, medpost, name) {
  pre <- rsdata %>%
    filter(sos_location == "HF in-patient") %>%
    group_by(shf_ef_cat) %>%
    count(!!sym(medpre)) %>%
    mutate(
      per = fn(n / sum(n) * 100, 1),
      nper = paste0(n, " (", per, "%)")
    ) %>%
    ungroup() %>%
    pivot_wider(id_cols = !!sym(medpre), names_from = shf_ef_cat, values_from = nper) %>%
    mutate(Medication = paste0("Prior ", name, " ", !!sym(medpre))) %>%
    select(Medication, !!!syms(levels(rsdata$shf_ef_cat)))

  post <- rsdata %>%
    filter(sos_location == "HF in-patient") %>%
    group_by(shf_ef_cat) %>%
    count(!!sym(medpost)) %>%
    mutate(
      per = fn(n / sum(n) * 100, 1),
      nper = paste0(n, " (", per, "%)")
    ) %>%
    ungroup() %>%
    pivot_wider(id_cols = !!sym(medpost), names_from = shf_ef_cat, values_from = nper) %>%
    mutate(Medication = paste0("Post ", name, " ", !!sym(medpost))) %>%
    select(Medication, !!!syms(levels(rsdata$shf_ef_cat)))

  out <- bind_rows(pre, post)
}
```

```{r tabontreatall, cache=cacheon, dependson="tabontreatallfunc"}
# HFrEF
mra <- funcdesk(medpre = "ddr_mra_prior", medpost = "ddr_mra_post", name = "MRA")
rasi <- funcdesk(medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", name = "RASi")
bbl <- funcdesk(medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", name = "Bbl")
loop <- funcdesk(medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post", name = "No Loop diuretics")

all <- bind_rows(mra, rasi, bbl, loop)

write.xlsx(all, paste0("./output/tabs/deskontreatmentall_", Sys.Date(), ".xlsx"), rowNames = FALSE)

default_kable(all,
  caption = "Patients on treatment after 1st HFH"
)
```
