```{r treatdisccoxregsub, cache=cacheon}

funccoxreg <- function(time, event, gfrcat, medpre, medpost, medname, discini2) {
  out <- data.frame(matrix(NA, ncol = 10, nrow = 3))

  if (discini2 == "discontinuation") {
    valmedpre <- "Yes"
    valmedpost <- "No"
    data <- rsdata %>% mutate(!!sym(medpost) := relevel(!!sym(medpost), ref = "Yes"))
  }
  if (discini2 == "initiation") {
    valmedpre <- "No"
    valmedpost <- "Yes"
    data <- rsdata %>% mutate(!!sym(medpost) := relevel(!!sym(medpost), ref = "No"))
  }

  colnames(out) <- c("Prior medication", "Model", levels(data %>% pull(!!sym(medpost))), "incforest", "loghr", "lci", "uci", "hrci", "pval")

  out[1:3, 1] <- rep(medname, 3)

  # incidence
  out[1, 2] <- "No event, sum py, incidence per 1000 py"
  ev <- data %>%
    filter(sos_location == "HF in-patient" & shf_gfrckdepi_cat2 %in% gfrcat & !!sym(medpre) == valmedpre) %>%
    group_by(!!sym(medpost)) %>%
    summarise(
      ev = sum(!!sym(event) == "Yes"),
      .groups = "rowwise"
    )

  s <- data %>%
    filter(sos_location == "HF in-patient" & shf_gfrckdepi_cat2 %in% gfrcat & !!sym(medpre) == valmedpre) %>%
    group_by(!!sym(medpost)) %>%
    summarise(
      s = sum(!!sym(time) / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s / 1000)

  out[1, 3:4] <- paste0(
    ev$ev, ", ",
    fn(s$s, dig = 0), ", ",
    fn(r$rate, dig = 0), " (",
    fn(r$lower, dig = 0), "-",
    fn(r$upper, dig = 0), ")"
  )

  out[1, 5] <- paste0(
    fn(r$rate[2], dig = 0), " (",
    fn(r$lower[2], dig = 0), "-",
    fn(r$upper[2], dig = 0), ")",
    " vs. ",
    fn(r$rate[1], dig = 0), " (",
    fn(r$lower[1], dig = 0), "-",
    fn(r$upper[1], dig = 0), ")"
  )

  # crude cox reg
  out[2, 2] <- "Crude HR (95% CI), p"
  mod <- coxph(formula(paste0("Surv(", time, ", ", event, " == 'Yes') ~ ", medpost)),
    data = data %>% filter(sos_location == "HF in-patient" & shf_gfrckdepi_cat2 %in% gfrcat & !!sym(medpre) == valmedpre)
  )
  smod <- summary(mod)

  out[2, 3:4] <- c("ref", paste0(
    fn(smod$conf.int[1], dig = 1),
    " (", fn(smod$conf.int[3], dig = 1),
    "-", fn(smod$conf.int[4], dig = 1), "), ",
    fn(smod$coefficients[5], dig = 3, p = TRUE)
  ))

  # adj cox reg

  modvarstmp <- modvars
  modvarstmp <- modvarstmp[modvarstmp != "shf_gfrckdepi_cat"]

  out[3, 2] <- "Adjusted HR (95% CI), p"
  amod <- hf_coxph_mids(formula(paste0(
    "Surv(", time, ",", event, " == 'Yes') ~ relevel(",
    medpost, ", ref = '", valmedpre, "') + ", paste(modvarstmp, collapse = " + ")
  )),
  data = imp,
  subset = expr(sos_location == "HF in-patient" & shf_gfrckdepi_cat2 %in% gfrcat & !!sym(medpre) == valmedpre)
  )
  asmod <- summary(pool(amod))

  # for forestplot
  out[3, 6] <- asmod$estimate[1]
  out[3, 7] <- asmod$estimate[1] - global_z05 * asmod$std.error[1]
  out[3, 8] <- asmod$estimate[1] + global_z05 * asmod$std.error[1]
  out[3, 9] <- paste0(
    fn(exp(asmod$estimate[1]), dig = 1),
    " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 1),
    "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 1), ")"
  )
  out[3, 10] <- fn(asmod$p.value[1], dig = 3, p = TRUE)

  out[3, 3:4] <- c("ref", paste0(out[3, 9], ", ", out[3, 10]))

  return(out)
}

funccoxreg2 <- function(time2, event2, discini) {
  # HFrEF
  out1 <- funccoxreg(
    time = time2, event = event2, gfrcat = ">=60", medpre = "ddr_mra_prior",
    medpost = "ddr_mra_post", medname = "MRA", discini2 = discini
  )
  out1 <- rbind(out1, funccoxreg(
    time = time2, event = event2, gfrcat = ">=60", medpre = "ddr_mra_prior8m",
    medpost = "ddr_mra_post", medname = "MRA 2 dd/8 mo", discini2 = discini
  ))

  out1 <- rbind(out1, funccoxreg(
    time = time2, event = event2, gfrcat = ">=60", medpre = "ddr_rasi_prior",
    medpost = "ddr_rasi_post", medname = "RASi/ARNi", discini2 = discini
  ))
  out1 <- rbind(out1, funccoxreg(
    time = time2, event = event2, gfrcat = ">=60", medpre = "ddr_rasi_prior8m",
    medpost = "ddr_rasi_post", medname = "RASi/ARNi 2 dd/8 mo", discini2 = discini
  ))

  out1 <- rbind(out1, funccoxreg(
    time = time2, event = event2, gfrcat = ">=60", medpre = "ddr_bbl_prior",
    medpost = "ddr_bbl_post", medname = "Betablocker", discini2 = discini
  ))
  out1 <- rbind(out1, funccoxreg(
    time = time2, event = event2, gfrcat = ">=60", medpre = "ddr_bbl_prior8m",
    medpost = "ddr_bbl_post", medname = "Betablocker 2 dd/8 mo", discini2 = discini
  ))

  out1 <- rbind(out1, funccoxreg(
    time = time2, event = event2,
    gfrcat = ">=60", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic", discini2 = discini
  ))
  out1 <- rbind(out1, funccoxreg(
    time = time2, event = event2,
    gfrcat = ">=60", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic 2 dd/8 mo", discini2 = discini
  ))

  # HFmrEF
  out2 <- funccoxreg(
    time = time2, event = event2, gfrcat = "<60", medpre = "ddr_mra_prior",
    medpost = "ddr_mra_post", medname = "MRA", discini2 = discini
  )
  out2 <- rbind(out2, funccoxreg(
    time = time2, event = event2, gfrcat = "<60", medpre = "ddr_mra_prior8m",
    medpost = "ddr_mra_post", medname = "MRA 2 dd/8 mo", discini2 = discini
  ))

  out2 <- rbind(out2, funccoxreg(
    time = time2, event = event2, gfrcat = "<60", medpre = "ddr_rasi_prior",
    medpost = "ddr_rasi_post", medname = "RASi/ARNi", discini2 = discini
  ))
  out2 <- rbind(out2, funccoxreg(
    time = time2, event = event2, gfrcat = "<60", medpre = "ddr_rasi_prior8m",
    medpost = "ddr_rasi_post", medname = "RASi/ARNi 2 dd/8 mo", discini2 = discini
  ))

  out2 <- rbind(out2, funccoxreg(
    time = time2, event = event2, gfrcat = "<60", medpre = "ddr_bbl_prior",
    medpost = "ddr_bbl_post", medname = "Betablocker", discini2 = discini
  ))
  out2 <- rbind(out2, funccoxreg(
    time = time2, event = event2, gfrcat = "<60", medpre = "ddr_bbl_prior8m",
    medpost = "ddr_bbl_post", medname = "Betablocker 2 dd/8 mo", discini2 = discini
  ))

  out2 <- rbind(out2, funccoxreg(
    time = time2, event = event2,
    gfrcat = "<60", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic", discini2 = discini
  ))
  out2 <- rbind(out2, funccoxreg(
    time = time2, event = event2,
    gfrcat = "<60", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic 2 dd/8 mo", discini2 = discini
  ))

  outprint <- cbind(
    out1[, 1:4],
    out2[, 3:4]
  )

  outforest1 <-
    out1 %>%
    mutate(cons = str_detect(`Prior medication`, "2 dd/8 mo")) %>%
    filter(Model != "Crude HR (95% CI), p" &
      !cons) %>%
    mutate(
      incforest = if_else(Model == "Adjusted HR (95% CI), p", lag(incforest), incforest),
      hf = ">=60"
    ) %>%
    filter(Model %in% c("Adjusted HR (95% CI), p")) %>%
    select(`Prior medication`, hf, incforest, loghr:pval)

  outforest2 <-
    out2 %>%
    mutate(cons = str_detect(`Prior medication`, "2 dd/8 mo")) %>%
    filter(Model != "Crude HR (95% CI), p" &
      !cons) %>%
    mutate(
      incforest = if_else(Model == "Adjusted HR (95% CI), p", lag(incforest), incforest),
      hf = "<60"
    ) %>%
    filter(Model %in% c("Adjusted HR (95% CI), p")) %>%
    select(`Prior medication`, hf, incforest, loghr:pval)

  outforest <- bind_rows(outforest1, outforest2)

  write.xlsx(outprint, paste0("./output/tabs/coxreg_", event2, "_", discini, "_eGFR_", Sys.Date(), ".xlsx"), rowNames = FALSE)

  ## fix in order to use escape = TRUE
  colnames(outprint) <- sanitize_text(colnames(outprint))

  return(out <- list(outprint = outprint, outforest = outforest))
}
```

```{r treatdisccoxregforestsub, cache=cacheon, dependson=c("treatdisccoxregsub"), fig.width=10, fig.height=7}

forestfunc <- function(data, discini, axismy = NULL) {
  foresttmp <- tibble(
    hf = c(
      paste0("MRA ", discini),
      paste0("RASi/ARNi ", discini),
      paste0("Betablocker ", discini),
      paste0("Loop diuretic ", discini)
    ),
    `Prior medication` = c(
      "MRA",
      "RASi/ARNi",
      "Betablocker",
      "Loop diuretic"
    )
  )
  forest <- bind_rows(foresttmp, data) %>%
    mutate(
      priormedno = case_when(
        `Prior medication` == "MRA" ~ 1,
        `Prior medication` == "RASi/ARNi" ~ 2,
        `Prior medication` == "Betablocker" ~ 3,
        `Prior medication` == "Loop diuretic" ~ 4,
      ),
      hfno = case_when(
        hf == ">=60" ~ 2,
        hf == "<60" ~ 3,
        TRUE ~ 1
      )
    ) %>%
    arrange(priormedno, hfno)

  forest <- forest %>%
    mutate(
      order = n():1,
      cols = case_when(
        hf == ">=60" ~ global_cols[4],
        hf == "<60" ~ global_cols[2]
      ),
      hf = case_when(
        hf == ">=60" ~ "eGFR \u226560",
        hf == "<60" ~ "eGFR <60",
        TRUE ~ hf
      )
    )

  cextext <- 1.3

  if (is.null(axismy)) {
    m1 <- round(exp(min(as.numeric(forest$lci), na.rm = T)), 1)
    m2 <- round(exp(max(as.numeric(forest$uci), na.rm = T)), 1)

    axismy <- c(m1, 1, m2)
  }
  ylim <- c(min(axismy), max(axismy))

  # c(bottom, left, top, right)
  par(mar = c(3.5, 32, 0.5, 10.5) + 0.2)

  plot(forest$loghr, forest$order,
    cex = 2,
    xlim = log(ylim),
    xlab = "",
    cex.lab = cextext,
    ylim = c(1, max(forest$order) + 1),
    axes = FALSE,
    ylab = NA,
    main = NA,
    type = "p",
    pch = 22,
    bg = forest$cols,
    col = forest$cols,
    xaxs = "i"
  )

  for (i in 1:nrow(forest)) {
    if (!is.na(forest$lci[i])) {
      matplot(c(forest$lci[i], forest$uci[i]), c(forest$order[i], forest$order[i]),
        type = "l", add = TRUE, col = forest$cols[i], cex = 1, lwd = 2.5
      )
    }
  }

  matplot(c(log(1), log(1)), c(-1, max(forest$order)), type = "l", lwd = 1, lty = 3, add = TRUE, col = 1)

  axis(1,
    cex.axis = cextext, at = log(axismy),
    labels = axismy, gap.axis = -100000
  )

  axis(2,
    at = forest %>% filter(hfno == 1) %>% pull(order),
    labels = forest %>% filter(hfno == 1) %>% pull(hf),
    cex.axis = cextext, tick = FALSE, las = 2, line = 16, hadj = 1, font = 2
  )
  axis(2,
    at = forest %>% filter(hfno != 1) %>% pull(order),
    labels = forest %>% filter(hfno != 1) %>% pull(hf),
    cex.axis = cextext, tick = FALSE, las = 2, line = 16, hadj = 1
  )

  axis(2,
    at = max(forest$order) + 1,
    labels = "Incidence rate",
    cex.axis = cextext, tick = FALSE, las = 2, line = 7.5, hadj = 0.5, font = 2
  )
  axis(2,
    at = forest %>% pull(order),
    labels = forest %>% pull(incforest),
    cex.axis = cextext, tick = FALSE, las = 2, line = 7.5, hadj = 0.5
  )

  axis(2,
    at = max(forest$order) + 1,
    labels = "HR (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = -11.5, hadj = 0.5, font = 2
  )
  axis(2,
    at = forest %>% pull(order),
    labels = forest %>% pull(hrci),
    cex.axis = cextext, tick = FALSE, las = 2, line = -11.5, hadj = 0.5
  )

  axis(2,
    at = max(forest$order) + 1,
    labels = "P-value",
    cex.axis = cextext, tick = FALSE, las = 2, line = -16.9, hadj = 0.5, font = 2
  )
  axis(2,
    at = forest %>% pull(order),
    labels = forest %>% pull(pval),
    cex.axis = cextext, tick = FALSE, las = 2, line = -16.9, hadj = 0.5
  )

  axis(1,
    at = (log(ylim[2]) - abs(log(ylim[1]))) / 2, cex.axis = cextext,
    labels = "HR (95% CI)", line = 1.5, tick = FALSE
  )
}
```

```{r treatdisccoxregdeathsub, cache=cacheon, dependson="treatdisccoxregsub"}

discdatadeath <- funccoxreg2(time2 = "sos_outtime_death3y", event2 = "sos_out_death3y", discini = "discontinuation")

default_kable(discdatadeath$outprint,
  caption = paste0("Treatment discontinuation - All-cause mortality within 3 years by eGFR HFrEF + HFmrEF"),
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```

```{r treatdisccoxregdeathforestsub, fig.cap = "Treatment discontinuation - All-cause mortality by eGFR HFrEF + HFmrEF", cache=cacheon, dependson=c("treatdisccoxregsub", "treatdisccoxregforestsub", "treatdisccoxregdeathsub"), fig.width=10, fig.height=7}

forestfunc(data = discdatadeath$outforest, discini = "discontinuation")
```

```{r treatdisccoxregdeathcvsub, cache=cacheon, dependson="treatdisccoxregsub"}

discdatadeathcv <- funccoxreg2(time2 = "sos_outtime_death3y", event2 = "sos_out_deathcv3y", discini = "discontinuation")

default_kable(discdatadeathcv$outprint,
  caption = "Treatment discontinuation - CV mortality within 3 years by eGFR HFrEF + HFmrEF",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```

```{r treatdisccoxregdeathcvforestsub, , fig.cap = "Treatment discontinuation - CV mortality by eGFR HFrEF + HFmrEF", cache=cacheon, dependson=c("treatdisccoxregsub", "treatdisccoxregforestsub", "treatdisccoxregdeathcvsub"), fig.width=10, fig.height=7}

forestfunc(data = discdatadeathcv$outforest, discini = "discontinuation")
```

```{r treatdisccoxreghosphfsub, cache=cacheon, dependson="treatdisccoxregsub"}

discdatahosphf <- funccoxreg2(time2 = "sos_outtime_hosphf3y", event2 = "sos_out_hosphf3y", discini = "discontinuation")

default_kable(discdatahosphf$outprint,
  caption = "Treatment discontinuation - First HF hospitalization within 3 years by eGFR HFrEF + HFmrEF",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```

```{r treatdisccoxregdeathcvhosphfpsub, cache=cacheon, dependson="treatdisccoxregsub"}

discdatadeathcvhosphf <- funccoxreg2(
  time2 = "sos_outtime_hosphf3y", event2 = "sos_out_deathcvhosphf3y",
  discini = "discontinuation"
)

default_kable(discdatadeathcvhosphf$outprint,
  caption = "Treatment discontinuation - CV mortality/first HF hospitalization within 3 years by eGFR HFrEF + HFmrEF",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```

```{r treatinicoxregdeathsub, cache=cacheon, dependson="treatdisccoxregsub"}

inidatadeath <- funccoxreg2(time2 = "sos_outtime_death3y", event2 = "sos_out_death3y", discini = "initiation")

default_kable(inidatadeath$outprint,
  caption = paste0("Treatment initiation - All-cause mortality within 3 years by eGFR HFrEF + HFmrEF"),
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```

```{r treatinicoxregdeathforestsub, fig.cap = "Treatment initiation - All-cause mortality by eGFR HFrEF + HFmrEF", cache=cacheon, dependson=c("treatdisccoxregsub", "treatdisccoxregforestsub", "treatinicoxregdeathsub"), fig.width=10, fig.height=7}

forestfunc(data = inidatadeath$outforest, discini = "initiation")
```

```{r treatinicoxregdeathcvsub, cache=cacheon, dependson="treatdisccoxregsub"}

inidatadeathcv <- funccoxreg2(time2 = "sos_outtime_death3y", event2 = "sos_out_deathcv3y", discini = "initiation")

default_kable(inidatadeathcv$outprint,
  caption = "Treatment initiation - CV mortality within 3 years by eGFR HFrEF + HFmrEF",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```

```{r treatinicoxregdeathcvforestsub, fig.cap = "Treatment initiation - CV mortality by eGFR HFrEF + HFmrEF", cache=cacheon, dependson=c("treatdisccoxregsub", "treatdisccoxregforestsub", "treatinicoxregdeathcvsub"), fig.width=10, fig.height=7}

forestfunc(data = inidatadeathcv$outforest, discini = "initiation")
```

```{r treatinicoxreghosphfsub, cache=cacheon, dependson="treatdisccoxregsub"}

inidatahosphf <- funccoxreg2(time2 = "sos_outtime_hosphf3y", event2 = "sos_out_hosphf3y", discini = "initiation")

default_kable(inidatahosphf$outprint,
  caption = "Treatment initiation - First HF hospitalization within 3 years by eGFR HFrEF + HFmrEF",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```

```{r treatinicoxregdeathcvhosphfpsub, cache=cacheon, dependson="treatdisccoxregsub"}

inidatadeathcvhosphf <- funccoxreg2(
  time2 = "sos_outtime_hosphf3y", event2 = "sos_out_deathcvhosphf3y",
  discini = "initiation"
)

default_kable(inidatadeathcvhosphf$outprint,
  caption = "Treatment initiation - CV mortality/first HF hospitalization within 3 years by eGFR HFrEF + HFmrEF",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, ">=60" = 2, "<60" = 2))
```
