```{r treatdisclogfuncs, cache=cacheon}

funclogreg <- function(efcat, medpre, medpost, medname, discini2) {
  out <- data.frame(matrix(NA, ncol = 9, nrow = 3))
  colnames(out) <- c("priormed", "model", levels(rsdata$sos_location), "logor", "lci", "uci", "orci", "pval")

  if (discini2 == "discontinuation") {
    valmedpre <- "Yes"
    valmedpost <- "No"
  }
  if (discini2 == "initiation") {
    valmedpre <- "No"
    valmedpost <- "Yes"
  }

  out[1:3, 1] <- rep(medname, 3)

  out[1:3, 2] <- c("n (%)", "Crude OR (95% CI), p", "Adjusted OR (95% CI), p")

  # desk stat
  ds <- rsdata %>%
    filter(shf_ef_cat %in% efcat & !!sym(medpre) == valmedpre) %>%
    group_by(sos_location) %>%
    count(!!sym(medpost)) %>%
    mutate(
      p = fn(n / sum(n) * 100, 1),
      np = paste0(n, " (", p, "%)")
    ) %>%
    filter(!!sym(medpost) == valmedpost) %>%
    select(-n, -p, -!!sym(medpost)) %>%
    pivot_wider(values_from = np, names_from = sos_location)

  out[1, 3:4] <- ds

  # crude log reg

  mod <- glm(formula(paste0(medpost, "== '", valmedpost, "' ~ sos_location")),
    family = binomial(link = "logit"),
    data = rsdata %>% filter(shf_ef_cat %in% efcat & !!sym(medpre) == valmedpre)
  )
  smod <- summary(mod)

  orcrude <- c("ref", paste0(
    fn(exp(smod$coefficients[2, 1]), dig = 1),
    " (", fn(exp(smod$coefficients[2, 1] - global_z05 * smod$coefficients[2, 2]), dig = 1),
    "-", fn(exp(smod$coefficients[2, 1] + global_z05 * smod$coefficients[2, 2]), dig = 1), "), ",
    fn(smod$coefficients[2, 4], dig = 3, p = TRUE)
  ))

  out[2, 3:4] <- orcrude

  # adj log reg

  amod <- hf_glm_mids(formula(paste0(
    medpost, "=='", valmedpost, "' ~ sos_location + ", paste(modvars, collapse = " + ")
  )),
  data = imp,
  subset = expr(shf_ef_cat %in% efcat & !!sym(medpre) == valmedpre)
  )
  asmod <- summary(pool(amod))

  # for forestplot
  out[3, 5] <- asmod$estimate[2]
  out[3, 6] <- asmod$estimate[2] - global_z05 * asmod$std.error[2]
  out[3, 7] <- asmod$estimate[2] + global_z05 * asmod$std.error[2]
  out[3, 8] <- paste0(
    fn(exp(asmod$estimate[2]), dig = 1),
    " (", fn(exp(asmod$estimate[2] - global_z05 * asmod$std.error[2]), dig = 1),
    "-", fn(exp(asmod$estimate[2] + global_z05 * asmod$std.error[2]), dig = 1), ")"
  )
  out[3, 9] <- fn(asmod$p.value[2], dig = 3, p = TRUE)

  out[3, 3:4] <- c("ref", paste0(out[3, 8], ", ", out[3, 9]))

  return(out)
}

funclogreg2 <- function(discini) {

  # HFrEF
  outref <- funclogreg(efcat = "HFrEF", medpre = "ddr_mra_prior", medpost = "ddr_mra_post", medname = "MRA", discini2 = discini)
  outref <- rbind(outref, funclogreg(efcat = "HFrEF", medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", medname = "MRA 2 dd/8 mo", discini2 = discini))

  outref <- rbind(outref, funclogreg(efcat = "HFrEF", medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", medname = "RASi/ARNi", discini2 = discini))
  outref <- rbind(outref, funclogreg(efcat = "HFrEF", medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post", medname = "RASi/ARNi 2 dd/8 mo", discini2 = discini))

  outref <- rbind(outref, funclogreg(efcat = "HFrEF", medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", medname = "Betablocker", discini2 = discini))
  outref <- rbind(outref, funclogreg(efcat = "HFrEF", medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post", medname = "Betablocker 2 dd/8 mo", discini2 = discini))

  outref <- rbind(outref, funclogreg(
    efcat = "HFrEF", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic", discini2 = discini
  ))
  outref <- rbind(outref, funclogreg(
    efcat = "HFrEF", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic 2 dd/8 mo", discini2 = discini
  ))

  # HFmrEF
  outmref <- funclogreg(efcat = "HFmrEF", medpre = "ddr_mra_prior", medpost = "ddr_mra_post", medname = "MRA", discini2 = discini)
  outmref <- rbind(outmref, funclogreg(efcat = "HFmrEF", medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post", medname = "MRA 2 dd/8 mo", discini2 = discini))

  outmref <- rbind(outmref, funclogreg(efcat = "HFmrEF", medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", medname = "RASi/ARNi", discini2 = discini))
  outmref <- rbind(outmref, funclogreg(
    efcat = "HFmrEF", medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post",
    medname = "RASi/ARNi 2 dd/8 mo", discini2 = discini
  ))

  outmref <- rbind(outmref, funclogreg(efcat = "HFmrEF", medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", medname = "Betablocker", discini2 = discini))
  outmref <- rbind(outmref, funclogreg(
    efcat = "HFmrEF", medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post",
    medname = "Betablocker 2 dd/8 mo", discini2 = discini
  ))

  outmref <- rbind(outmref, funclogreg(
    efcat = "HFmrEF", medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic", discini2 = discini
  ))
  outmref <- rbind(outmref, funclogreg(
    efcat = "HFmrEF", medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic 2 dd/8 mo", discini2 = discini
  ))

  # All
  outall <- funclogreg(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_mra_prior", medpost = "ddr_mra_post", medname = "MRA", discini2 = discini)
  outall <- rbind(outall, funclogreg(
    efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_mra_prior8m", medpost = "ddr_mra_post",
    medname = "MRA 2 dd/8 mo", discini2 = discini
  ))

  outall <- rbind(outall, funclogreg(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_rasi_prior", medpost = "ddr_rasi_post", medname = "RASi/ARNi", discini2 = discini))
  outall <- rbind(outall, funclogreg(
    efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_rasi_prior8m", medpost = "ddr_rasi_post",
    medname = "RASi/ARNi 2 dd/8 mo", discini2 = discini
  ))

  outall <- rbind(outall, funclogreg(efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_bbl_prior", medpost = "ddr_bbl_post", medname = "Betablocker", discini2 = discini))
  outall <- rbind(outall, funclogreg(
    efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_bbl_prior8m", medpost = "ddr_bbl_post",
    medname = "Betablocker 2 dd/8 mo", discini2 = discini
  ))

  outall <- rbind(outall, funclogreg(
    efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_loopdiuretic_prior", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic", discini2 = discini
  ))
  outall <- rbind(outall, funclogreg(
    efcat = c("HFrEF", "HFmrEF"), medpre = "ddr_loopdiuretic_prior8m", medpost = "ddr_loopdiuretic_post",
    medname = "Loop diuretic 2 dd/8 mo", discini2 = discini
  ))

  outprint <- cbind(
    outref %>% select(priormed:`HF in-patient`),
    outmref %>% select(`Out-patient`:`HF in-patient`),
    outall %>% select(`Out-patient`:`HF in-patient`)
  )

  outforestref <-
    outref %>%
    mutate(cons = str_detect(priormed, "2 dd/8 mo")) %>%
    filter(model %in% c("n (%)", "Adjusted OR (95% CI), p") &
      !cons) %>%
    mutate(
      ds = paste0(`HF in-patient`, " vs. ", `Out-patient`),
      ds = if_else(model == "Adjusted OR (95% CI), p", lag(ds), ds),
      hf = "HFrEF"
    ) %>%
    filter(model %in% c("Adjusted OR (95% CI), p")) %>%
    select(priormed, hf, ds, logor:pval)

  outforestmref <-
    outmref %>%
    mutate(cons = str_detect(priormed, "2 dd/8 mo")) %>%
    filter(model %in% c("n (%)", "Adjusted OR (95% CI), p") &
      !cons) %>%
    mutate(
      ds = paste0(`HF in-patient`, " vs. ", `Out-patient`),
      ds = if_else(model == "Adjusted OR (95% CI), p", lag(ds), ds),
      hf = "HFmrEF"
    ) %>%
    filter(model %in% c("Adjusted OR (95% CI), p")) %>%
    select(priormed, hf, ds, logor:pval)

  outforestall <-
    outall %>%
    mutate(cons = str_detect(priormed, "2 dd/8 mo")) %>%
    filter(model %in% c("n (%)", "Adjusted OR (95% CI), p") &
      !cons) %>%
    mutate(
      ds = paste0(`HF in-patient`, " vs. ", `Out-patient`),
      ds = if_else(model == "Adjusted OR (95% CI), p", lag(ds), ds),
      hf = "All (HFrEF + HFmrEF)"
    ) %>%
    filter(model %in% c("Adjusted OR (95% CI), p")) %>%
    select(priormed, hf, ds, logor:pval)

  outforest <- bind_rows(outforestref, outforestmref, outforestall)

  write.xlsx(outprint, paste0("./output/tabs/logreg_", discini, "_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

  ## fix in order to use escape = TRUE
  colnames(outprint) <- sanitize_text(c("Prior medication", "Model", rep(c("Out-patient", "HF in-patient"), 3)))

  return(out <- list(outprint = outprint, outforest = outforest))
}
```

```{r treatdisclogforestfunc, cache=cacheon}

funclogregforest <- function(data, discini, axismy) {
  foresttmp <- tibble(
    hf = c(
      paste0("MRA ", discini),
      paste0("RASi/ARNi ", discini),
      paste0("Betablocker ", discini),
      paste0("Loop diuretic ", discini)
    ),
    priormed = c(
      "MRA",
      "RASi/ARNi",
      "Betablocker",
      "Loop diuretic"
    )
  )
  forest <- bind_rows(foresttmp, data) %>%
    mutate(
      priormedno = case_when(
        priormed == "MRA" ~ 1,
        priormed == "RASi/ARNi" ~ 2,
        priormed == "Betablocker" ~ 3,
        priormed == "Loop diuretic" ~ 4,
      ),
      hfno = case_when(
        hf == "HFrEF" ~ 2,
        hf == "HFmrEF" ~ 3,
        hf == "All (HFrEF + HFmrEF)" ~ 4,
        TRUE ~ 1
      )
    ) %>%
    arrange(priormedno, hfno)

  forest <- forest %>%
    mutate(
      order = n():1,
      cols = case_when(
        hf == "HFrEF" ~ global_kicols[2],
        hf == "HFmrEF" ~ global_kicols[3],
        hf == "All (HFrEF + HFmrEF)" ~ global_kicols[1]
      )
    )

  cextext <- 1.1

  # exp(min(as.numeric(forest$lci), na.rm = T))
  # exp(max(as.numeric(forest$uci), na.rm = T))
  ylim <- c(min(axismy), max(axismy))

  # c(bottom, left, top, right)
  par(mar = c(3, 26, 0.5, 10) + 0.2)

  plot(forest$logor, forest$order,
    cex = 2,
    xlim = log(ylim),
    xlab = "",
    cex.lab = cextext,
    ylim = c(1, max(forest$order) + .4),
    axes = FALSE,
    ylab = NA,
    main = NA,
    type = "p",
    pch = 22,
    bg = forest$cols,
    col = forest$cols,
    xaxs = "i"
  )

  for (i in 1:nrow(forest)) {
    if (!is.na(forest$lci[i])) {
      matplot(c(forest$lci[i], forest$uci[i]), c(forest$order[i], forest$order[i]),
        type = "l", add = TRUE, col = forest$cols[i], cex = 1, lwd = 2
      )
    }
  }

  matplot(c(log(1), log(1)), c(-1, max(forest$order)), type = "l", lwd = 1, lty = 3, add = TRUE, col = 1)

  axis(1,
    cex.axis = cextext, at = log(axismy),
    labels = axismy, gap.axis = -100000
  )

  axis(2,
    at = forest %>% filter(hfno == 1) %>% pull(order),
    labels = forest %>% filter(hfno == 1) %>% pull(hf),
    cex.axis = cextext, tick = FALSE, las = 2, line = 12, hadj = 1, font = 2
  )
  axis(2,
    at = forest %>% filter(hfno != 1) %>% pull(order),
    labels = forest %>% filter(hfno != 1) %>% pull(hf),
    cex.axis = cextext, tick = FALSE, las = 2, line = 12, hadj = 1
  )

  axis(2,
    at = max(forest$order) + 1,
    labels = "Events",
    cex.axis = cextext, tick = FALSE, las = 2, line = 5.5, hadj = 0.5, font = 2
  )
  axis(2,
    at = forest %>% pull(order),
    labels = forest %>% pull(ds),
    cex.axis = cextext, tick = FALSE, las = 2, line = 5.5, hadj = 0.5
  )

  axis(2,
    at = max(forest$order) + 1,
    labels = "OR (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = -18, hadj = 0.5, font = 2
  )
  axis(2,
    at = forest %>% pull(order),
    labels = forest %>% pull(orci),
    cex.axis = cextext, tick = FALSE, las = 2, line = -18, hadj = 0.5
  )

  axis(2,
    at = max(forest$order) + 1,
    labels = "P-value",
    cex.axis = cextext, tick = FALSE, las = 2, line = -23, hadj = 0.5, font = 2
  )
  axis(2,
    at = forest %>% pull(order),
    labels = forest %>% pull(pval),
    cex.axis = cextext, tick = FALSE, las = 2, line = -23, hadj = 0.5
  )

  axis(1,
    at = (log(ylim[2]) - abs(log(ylim[1]))) / 2, cex.axis = cextext,
    labels = "OR (95% CI)", line = 1, tick = FALSE
  )
}
```

```{r treatdisc, cache=cacheon, dependson=c("treatdisclogfuncs")}

discdata <- funclogreg2(discini = "discontinuation")

default_kable(discdata$outprint,
  caption = "Treatment discontinuation",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, "HFrEF" = 2, " HFmrEF" = 2, "HFrEF + HFmrEF" = 2))
```

```{r treatdiscforest, fig.cap = "Treatment discontinuation", cache=cacheon, dependson=c("treatdisclogfuncs", "treatdisc", "treatdisclogforestfunc"), fig.width=10, fig.height=7}

funclogregforest(data = discdata$outforest, discini = "discontinuation", axismy = c(0.1, 0.5, 1, 1.5, 2.5))
```

```{r treatini, cache=cacheon, dependson=c("treatdisclogfuncs")}

inidata <- funclogreg2(discini = "initiation")

default_kable(inidata$outprint,
  caption = "Treatment initiation",
  escape = TRUE
) %>%
  landscape() %>%
  add_header_above(c(" " = 1, " " = 1, "HFrEF" = 2, " HFmrEF" = 2, "HFrEF + HFmrEF" = 2))
```

```{r treatiniforest, fig.cap = "Treatment initiation", cache=cacheon, dependson=c("treatdisclogfuncs", "treatini", "treatdisclogforestfunc"), fig.width=10, fig.height=7}

funclogregforest(inidata$outforest, discini = "initiation", axismy = c(1, 5, 10, 15, 25))
```
